### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by RlearnerR** [SimpleITK/SimpleITKRInstaller#32]
Hi,

I'm having problems with this installer - I would be very grateful for any advice! I've installed devtools, and made sure cmake and git are installed and functional. This doesn't seem to be a PCRE problem, but I'm new to this so I might be mistaken.

Thanks!
Max

```
> devtools::install_github("SimpleITK/SimpleITKRInstaller")
Downloading GitHub repo SimpleITK/SimpleITKRInstaller@master
✔  checking for file ‘/private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpcQCc2Z/remotes10b6516ee3d4/SimpleITK-SimpleITKRInstaller-ec1d304/DESCRIPTION’ ...
─  preparing ‘SimpleITK’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SimpleITK/.circleci’
─  creating default NAMESPACE file
─  building ‘SimpleITK_1.2.0.tar.gz’
   
* installing *source* package ‘SimpleITK’ ...
/private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpktLefj/R.INSTALL178139caa98d/SimpleITK
Cloning into 'SimpleITK'...
Note: checking out 'v1.2.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d6026bbd Merge topic 'FixRdImageViewDocumentation'
./configure: line 52: cmake: command not found
ERROR: configuration failed for package ‘SimpleITK’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/SimpleITK’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T//RtmpcQCc2Z/file10b622259414/SimpleITK_1.2.0.tar.gz’ had non-zero exit status
> 
```

**Comment by blowekamp** [comment]
Hello,

How did you install CMake? And are you able to execute it at the same command line prompt where you are trying to build SimpleITK R?

You may need to add CMake to you path with:
```
export PATH=/Applications/CMake.app/Contents/bin:${PATH}
```

**Comment by RlearnerR** [comment]
Thank you for the help! I downloaded it onto my Mac - I'm assuming it's installed okay as I'm able to get the following in R studio:
```
> cmaker::cmakeVersion()
[1] "3.9.3"
```
I'm just trying to install from the R Studio console, I haven't tried from the command line/terminal. Is there a way of me adding cmake to the path in R Studio, or am I going about this the wrong way? 

Apologies if I've misunderstood anything, as I say this is all very new to me. Thank you again!

**Comment by blowekamp** [comment]
You can try executing the following R command before:
```
Sys.setenv(PATH=paste("/Applications/CMake.app/Contents/bin/",Sys.getenv("PATH"),sep=":"))

```

**Comment by RlearnerR** [comment]
Thanks for this! I used this, and got past the previous fail point, but the installation is having further problems.

It first failed with the PCRE compilation, with the same log as reported in the other issue posted by JEFworks. I followed your link about XCode 10 behaviour changes, and installed /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg to correct the issue with headers. This seemed to fix the PCRE problem.

It has now failed again, after a few hours of installing. I've included the most recent part of the log below - once again I'd be hugely grateful for any advice. Thank you. 

```
[ 98%] Building CXX object Code/BasicFilters/src/CMakeFiles/SimpleITK_ITKImageIntensity.dir/sitkXorImageFilter.cxx.o
[ 99%] Linking CXX static library ../../../lib/libSimpleITK_ITKImageIntensity-1.2.a
[ 99%] Built target SimpleITK_ITKImageIntensity
Scanning dependencies of target SimpleITKIO
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageFileReader.cxx.o
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageFileWriter.cxx.o
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageReaderBase.cxx.o
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageSeriesReader.cxx.o
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageSeriesWriter.cxx.o
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImportImageFilter.cxx.o
[ 99%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkShow.cxx.o
[100%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageIOUtilities.cxx.o
[100%] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageViewer.cxx.o
[100%] Linking CXX static library ../../../lib/libSimpleITKIO-1.2.a
[100%] Built target SimpleITKIO
Scanning dependencies of target SimpleITKBasicFilters1
[100%] Building CXX object Code/BasicFilters/src/CMakeFiles/SimpleITKBasicFilters1.dir/sitkAdditionalProcedures.cxx.o
[100%] Linking CXX static library ../../../lib/libSimpleITKBasicFilters1-1.2.a
[100%] Built target SimpleITKBasicFilters1
Scanning dependencies of target SimpleITKRpackageData
[100%] Generating /private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/SimpleITK-build/ExternalData/Wrapping/R/Packaging/SimpleITK/inst/extdata/cthead1-Float.mha
-- Fetching "https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/25de5707b18c0c684fd5fa30351bf787"
-- [download 0% complete]
-- [download 32% complete]
-- [download 64% complete]
-- [download 96% complete]
-- [download 100% complete]
-- Downloaded object: "/private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/ExternalData/Objects/MD5/25de5707b18c0c684fd5fa30351bf787"
[100%] Generating /private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/SimpleITK-build/ExternalData/Wrapping/R/Packaging/SimpleITK/inst/extdata/cthead1.png
-- Fetching "https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/b23198c9e44a48edfd5b83f075eb455c"
-- [download 0% complete]
-- [download 56% complete]
-- [download 100% complete]
-- Downloaded object: "/private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/ExternalData/Objects/MD5/b23198c9e44a48edfd5b83f075eb455c"
[100%] Generating /private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/SimpleITK-build/ExternalData/Wrapping/R/Packaging/SimpleITK/man/sitkRdfiles.tar.gz
-- Fetching "https://erie.nlm.nih.gov/SimpleITKExternalData/MD5/f39ee5b792b0f3efb52d2601fe01022e"
-- [download 0% complete]
-- [download 8% complete]
-- [download 16% complete]
-- [download 25% complete]
-- [download 33% complete]
-- [download 41% complete]
-- [download 49% complete]
-- [download 57% complete]
-- [download 66% complete]
-- [download 74% complete]
-- [download 82% complete]
-- [download 90% complete]
-- [download 98% complete]
-- [download 100% complete]
-- Downloaded object: "/private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/ExternalData/Objects/MD5/f39ee5b792b0f3efb52d2601fe01022e"
[100%] Built target SimpleITKRpackageData
[100%] Swig source to generate R wrapping
Scanning dependencies of target SimpleITK_R
[100%] Building CXX object Wrapping/R/CMakeFiles/SimpleITK_R.dir/SimpleITKR_wrap.cxx.o
[100%] Building CXX object Wrapping/R/CMakeFiles/SimpleITK_R.dir/sitkRCommand.cxx.o
[100%] Building CXX object Wrapping/R/CMakeFiles/SimpleITK_R.dir/sitkRArray.cxx.o
[100%] Linking CXX shared module Packaging/SimpleITK/src/SimpleITK.so
/bin/sh: line 0: cd: /private/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T/RtmpMjC5SK/R.INSTALL2660527b5973/SimpleITK/SITK/Build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man: No such file or directory
make[5]: *** [Wrapping/R/Packaging/SimpleITK/src/SimpleITK.so] Error 1
make[4]: *** [Wrapping/R/CMakeFiles/SimpleITK_R.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
ERROR: configuration failed for package ‘SimpleITK’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/SimpleITK’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/85/1sjw0bfs72xbyvs_h_m0xzpw0000gn/T//RtmpUx2QjM/file25883108832c/SimpleITK_1.2.0.tar.gz’ had non-zero exit status
```

**Comment by blowekamp** [comment]
@richardbeare We saw the same issue on the Azure CI build

I was able to reproduce it locally with the RInstaller script, but it does not occur when building SimpleITK directly from it's source.

**Comment by richardbeare** [comment]
Interesting. Which version of OSX are you both using? I'm setting a local run going now.

**Comment by blowekamp** [comment]
I am working on a patch. It appear to be related to the destination path not being created before a copy.

**Comment by blowekamp** [comment]
SimpleITK/SimpleITK#701 should fix this issue.

**Comment by RlearnerR** [comment]
I'm on Mojave 10.14.3. Unfortunately I'm still having the same problem - go I need to change how I'm installing this to include your patch? I've just tried the same input in R Studio (below), but it failed again - the log looks identical to the post above. Thank you!!

```
Sys.setenv(PATH=paste("/Applications/CMake.app/Contents/bin/",Sys.getenv("PATH"),sep=":"))
devtools::install_github("SimpleITK/SimpleITKRInstaller")
```

**Comment by blowekamp** [comment]
I just merged the pull request #31, which include the needed SimpleITK fix and a bump to the SimpleITKR version. Your above line should work now.
